version: 0.1
phases:
  install:
    commands:
      - mvn clean package
      - aws cloudformation package --template-file template.yaml --s3-bucket codepipeline-ap-south-1-182844376226
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - template.yaml
    - outputSamTemplate.yaml


