version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "project1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3y6a7evpc8z7"
s3_prefix = "project1"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
