--- 
AWSTemplateFormatVersion: "2010-09-09"
Description: "sam-app Sample SAM Template for sam-app\n"
Globals: 
  Function: 
    Timeout: 20
Metadata: 
  ? "AWS::ServerlessRepo::Application"
  : 
    Author: user1
    Description: "hello world"
    HomePageUrl: "https://github.com/amoljohare/final-test-master.git"
    Labels: 
      - tests
    LicenseUrl: LICENSE.txt
    Name: sam-app-2
    ReadmeUrl: README.md
    SemanticVersion: "0.0.1"
    SourceCodeUrl: "https://github.com/amoljohare/final-test-master.git"
    SpdxLicenseId: Apache-2.0
Outputs: 
  HelloWorldApi: 
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction: 
    Description: "Hello World Lambda Function ARN"
    Value: HelloWorldFunction.Arn
  HelloWorldFunctionIamRole: 
    Description: "Implicit IAM Role created for Hello World function"
    Value: HelloWorldFunctionRole.Arn
Resources: 
  HelloWorldFunction: 
    Properties: 
      CodeUri: "."
      Events: 
        HelloWorld: 
          Properties: 
            Method: get
            Path: /hello
          Type: Api
      Handler: "com.maven.cicdhelloworld.helloword::handleRequest"
      Runtime: java8
    Type: "AWS::Serverless::Function"
Transform: "AWS::Serverless-2016-10-31"
